# Generated by Django 3.2 on 2021-04-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210414_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Трейлер'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Фильм'),
        ),
    ]
