# Generated by Django 3.2 on 2021-04-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210414_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='avg_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2),
        ),
    ]
